In [2]:
my_text = "I have always wondered that will it be easy and fast to read a book if all the useless letters were removed from it"
my_text

'I have always wondered that will it be easy and fast to read a book if all the useless letters were removed from it'

In [3]:
words = my_text.split()

In [4]:
words

['I',
 'have',
 'always',
 'wondered',
 'that',
 'will',
 'it',
 'be',
 'easy',
 'and',
 'fast',
 'to',
 'read',
 'a',
 'book',
 'if',
 'all',
 'the',
 'useless',
 'letters',
 'were',
 'removed',
 'from',
 'it']

## Now we will be randomly scrambling the words present in above list.

In [5]:
import numpy as np

np.random.permutation(10)

array([0, 5, 8, 7, 1, 3, 4, 6, 9, 2])

In [6]:
np.random.permutation(10)

array([6, 8, 7, 9, 0, 3, 5, 1, 4, 2])

## We get random permutation each time we run it.

In [13]:
w = "rashu"
idx = np.random.permutation(len(w))
print(idx)
scrambled = [w[i] for i in idx]
scrambled

[1 0 4 2 3]


['a', 'r', 'u', 's', 'h']

In [14]:
w = "rashu"
idx = np.random.permutation(len(w))
print(idx)
scrambled = [w[i] for i in idx]
scrambled

[1 4 2 0 3]


['a', 'u', 's', 'r', 'h']

In [15]:
w = "rashu"
idx = np.random.permutation(len(w))
print(idx)
scrambled = [w[i] for i in idx]
scrambled

[0 1 3 2 4]


['r', 'a', 'h', 's', 'u']

You can clearly see that we get random order of the letters in the word everytime we run the above code.

In [16]:
# joining all the letters to form the word after scrambling

w = "rashu"
idx = np.random.permutation(len(w))
print(idx)
scrambled = "".join([w[i] for i in idx])
scrambled

[0 4 1 2 3]


'ruash'

In [19]:
# scrambling all the letters 

for wi in range(len(words)):
  thisword = words[wi]
  idx = np.random.permutation(len(thisword))
  words[wi] = "".join([thisword[i] for i in idx])

" ".join(words)

'I evah ylwsaa nodeewrd that wlil ti eb ysea nad satf to ader a kboo fi lla eht lsseesu eslrtet wree dmoevre rfom ti'

## Some words from above are readable while many are not. This is happening because we scrambled all the letters of each word.

In [23]:
# Now we will scramble all the words but in each word we will keep
# the first and the last character intact.

# We will also be ignoring the short words because there is no point of scrambling the 
# very short words.

words = my_text.split()

for wi in range(len(words)):
  if(len(words[wi]) < 4):
    continue
  
  thisword = words[wi][1:-1] # not taking into consideration the first and the last characters of the word.
  idx = np.random.permutation(len(thisword))
  words[wi] = words[wi][0] + ''.join([thisword[i] for i in idx]) + words[wi][-1]

' '.join(words)






'I hvae always werdneod taht wlil it be easy and fast to read a book if all the useelss ltreets were rveomed form it'

# You can easily read the above sentence although the words are scrambled above.

### Now we will use the technique where we will replace with random letters keeping the first and the last letters of the word intact. ( Here it is not necessary that we will replace with only those letters which are present in the word but we will replace with any random letters.)

In [24]:
import string
allletters = string.ascii_lowercase
allletters

'abcdefghijklmnopqrstuvwxyz'

In [26]:
np.random.randint(0,10,5) # will give 5 integers between 0 and 10, 10 excluded.

array([7, 8, 9, 6, 0])

In [27]:
words = my_text.split()

for wi in range(len(words)):
  if(len(words[wi]) < 4):
    continue
  
  thisword = words[wi][1:-1] # not taking into consideration the first and the last characters of the word.
  idx = np.random.randint(0,len(allletters),len(thisword))
  words[wi] = words[wi][0] + ''.join([allletters[i] for i in idx]) + words[wi][-1]

' '.join(words)

'I hrme arcqis wozrhbmd tzvt wzll it be etyy and fdst to rdtd a bdek if all the uxiuhis lipkmrs wjwe rrwztld frem it'

## So we can clearly see that above sentence is not readble if you already don't know the sentence.